name: tharwat_pharmacy
description: "Comprehensive Pharmacy Application built with Flutter and GetX for online pharmaceutical shopping, prescription orders, and delivery management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 

  flutter_localizations:
    sdk: flutter
  image_picker:
  cached_network_image:
  url_launcher: ^6.3.0
  get:
  google_fonts:
  flutter_otp_text_field:
  intl:
  device_preview:
  http:
  shared_preferences:
  dartz:
  dotted_border: 
  screen_go: ^1.1.7
  carousel_slider: ^5.0.0
  flutter_svg:
  flutter_image_compress: ^2.4.0
  mobile_scanner:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:

  uses-material-design: true

  assets:
    - lib/Images/

  